name = "Telence web"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate --schema prisma/schema.dev.prisma"
dev = "npx prisma db push --schema prisma/schema.dev.prisma && npx react-router dev"
